# mochou-p/game/Cargo.toml

[workspace]
members  = [
    "utils",
    "database/core",
    "game/protocol",
    "game/client",
    "game/server",
    "web/backend",
    "web/frontend"
]
resolver = "3"

[workspace.dependencies]
serde    = { version = "1.0.229", features = ["derive"] }
tokio    = { version = "1.53.1",  features = ["full"  ] }

