# mochou-p/game/web/backend/Cargo.toml

[package]
name          = "web_backend"
edition       = "2024"

[dependencies]
database_core = { path      = "../../database/core"                }
rspond        = { git       = "https://github.com/mochou-p/rspond" }
tokio         = { workspace = true                                 }
utils         = { path      = "../../utils"                        }
web_frontend  = { path      = "../frontend"                        }

