# mochou-p/game/web/backend/Cargo.toml

[package]
name         = "web_backend"
edition      = "2024"

[[bin]]
name         = "web_backend"

[dependencies]
web_frontend = { path    = "../frontend"                        }
#rspond       = { git     = "https://github.com/mochou-p/rspond" }
rspond       = { path    = "../../../rspond" } # TEMP
tokio        = { version = "1.53.1", features = ["full"]        }
rusqlite     = { version = "0.40.2", features = ["bundled"]     }

